version: 0.2

env:
  variables:
    DOCKER_IMAGE: deepanshu1411/react-sample-app:latest  # Your Docker Hub image name (username/repository:tag)
  secrets-manager:
    DOCKER_HUB_USERNAME: dockerhub/creds:username  # Replace 'dockerhub/creds' with your secret name and the field name for username
    DOCKER_HUB_PASSWORD: dockerhub/creds:password  # Replace 'dockerhub/creds' with your secret name and the field name for password
  image: aws/codebuild/standard:5.0  # This is the AWS CodeBuild image that supports Docker

phases:
  install:
    commands:
      - echo "Installing dependencies"
      # Docker Hub login using Secrets Manager values
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $DOCKER_IMAGE .

  post_build:
    commands:
      - echo "Pushing the Docker image to Docker Hub"
      - docker push $DOCKER_IMAGE
