version: 0.2

env:
  variables:
    DOCKER_IMAGE: deepanshu1411/react-sample-app:latest  # Update with your Docker Hub username and image name
  secrets-manager:
    DOCKER_HUB_USERNAME: dockerhub/creds:username  # Replace 'docker-hub-credentials' with your secret name
    DOCKER_HUB_PASSWORD: dockerhub/creds:password  # Replace 'docker-hub-credentials' with your secret name

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      # Ensure Docker is running
      - echo "Installing dependencies"
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t $DOCKER_IMAGE .

  post_build:
    commands:
      - echo "Pushing the Docker image to Docker Hub"
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - docker push $DOCKER_IMAGE
